version: "3"
services:
  mytelegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/wireguard:/etc/wireguard
    network_mode: host
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - WG_LOCAL_IP_HINT=${WG_LOCAL_IP_HINT}
    # ports:
    #   - 51830:51830/udp
    #    sysctls:
    #      - net.ipv4.conf.all.src_valid_mark=1
    privileged: true
    cap_add:
      - NET_ADMIN # Добавьте эту строку
    restart: always
