version: "3.8"
services:
  mytelegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wg_telegram_bot
    volumes:
      - /etc/wireguard:/etc/wireguard:rw
    environment:
      - TZ=UTC
    network_mode: host
    # ports:
    #   - 51830:51830/udp
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
